### ISSUE TITLE
USB_NeXT_Keyboard.ino:117:3: error: 'Keyboard' was not declared in this scope

### ISSUE THREAD

**Issue by markwbrown** [adafruit/USB-NeXT-Keyboard#3]
Offender is Keyboard.begin();

**Comment by ladyada** [comment]
make sure you're using the Leonardo core with Keyboard mode

**Comment by markwbrown** [comment]
For others that may experience this issue, check which version of the IDE's Boards you are running. The quick fix if you were on 1.6.9 like me, is to go Tools>Boards>Board Manager and Click on the Arduino AVR Boards by Arduino, select 1.6.2 from the dropdown "Select version". You'll save yourself from running down a rabbit hole of HID h and Keyboard.h errors. Thanks Ladyada for doing the heavy lifting. Cool project, and I'm typing on the old NeXT board now.
